// <auto-generated />
using System;
using FlowCare.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowCare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304123726_newDB")]
    partial class newDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowCare.Api.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SlotRetentionDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedStaffProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentContentType")
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<long?>("AttachmentSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffProfileId");

                    b.HasIndex("CustomerProfileId");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("ActorRole")
                        .HasColumnType("integer");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("TargetEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdImageContentType")
                        .HasColumnType("text");

                    b.Property<string>("IdImagePath")
                        .HasColumnType("text");

                    b.Property<long?>("IdImageSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("StaffProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DeletedAtUtc");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("StartTimeUtc");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.StaffProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.StaffServiceType", b =>
                {
                    b.Property<int>("StaffProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("StaffProfileId", "ServiceTypeId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("StaffServiceTypes");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Appointment", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.StaffProfile", "AssignedStaffProfile")
                        .WithMany("AssignedAppointments")
                        .HasForeignKey("AssignedStaffProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowCare.Api.Entities.CustomerProfile", "CustomerProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Api.Entities.Slot", "Slot")
                        .WithOne("Appointment")
                        .HasForeignKey("FlowCare.Api.Entities.Appointment", "SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaffProfile");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.CustomerProfile", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("FlowCare.Api.Entities.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.ServiceType", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.Branch", "Branch")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Slot", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.Branch", "Branch")
                        .WithMany("Slots")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Api.Entities.ServiceType", "ServiceType")
                        .WithMany("Slots")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Api.Entities.StaffProfile", "StaffProfile")
                        .WithMany("Slots")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.StaffProfile", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("FlowCare.Api.Entities.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.StaffServiceType", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.ServiceType", "ServiceType")
                        .WithMany("StaffServiceTypes")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Api.Entities.StaffProfile", "StaffProfile")
                        .WithMany("StaffServiceTypes")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.User", b =>
                {
                    b.HasOne("FlowCare.Api.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Branch", b =>
                {
                    b.Navigation("ServiceTypes");

                    b.Navigation("Slots");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.CustomerProfile", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.ServiceType", b =>
                {
                    b.Navigation("Slots");

                    b.Navigation("StaffServiceTypes");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.Slot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.StaffProfile", b =>
                {
                    b.Navigation("AssignedAppointments");

                    b.Navigation("Slots");

                    b.Navigation("StaffServiceTypes");
                });

            modelBuilder.Entity("FlowCare.Api.Entities.User", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("StaffProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
